[package]
authors = ["Gabriela Alexandra Moldovan"]
name = "rustc_codegen_ironox"
version = "0.0.0"

[lib]
name = "rustc_codegen_ironox"
path = "lib.rs"
crate-type = ["dylib"]
test = false

[dependencies]
ar = "0.6.0"
